### ISSUE TITLE
Could you please provide the pre-trained model for demo?

### ISSUE THREAD

**Issue by Da-He** [foamliu/Deep-Mobile-Matting#2]
Hi,
Thanks for you work!
I found that there is no pre-process.py file. And the pre-trained model does also not exist. As a result, I can not run the demo.
Could you please release your trained model weights file as well as other necessary files (if there are) for demo?
Thanks in advance.

Da

**Comment by InternetMaster1** [comment]
@Da-He Were you able to make this library run?

**Comment by Da-He** [comment]
> @Da-He Were you able to make this library run?

@InternetMaster1 I tried this repo 1.5 years ago and it did not work at that time. But it seems that there are some updates in the recent half year. Thus, I do not know its current status. I think it is the time to close this issue.
