### ISSUE TITLE
Bad training loss for "mobile net" backbone in deeplab

### ISSUE THREAD

**Issue by rainsun1** [foamliu/Deep-Mobile-Matting#3]
I trained the demo with "mobile net" backbone, but it could only reach to a alpha prediction loss of 0.1220 or so, which is far worse than "segnet".

Why should this happen? What is your loss? Thanks!

**Comment by foamliu** [comment]
I think the reason is too few params in dconv net. To compress decoder is much harder then encoder and you know why.
