### ISSUE TITLE
Integrating Mobile_Image_Matting into Android Project

### ISSUE THREAD

**Issue by charlizesmith** [foamliu/Deep-Mobile-Matting#4]
Hi,
Thanks for you work! 
its looking awesome output. 
I  want  to integrate your demo into android project. Is it possible to integrate model into android Project? If it possible, then How can i integrate this model into android project?
Can you please give some suggestions?
Thanks in advance.

**Comment by foamliu** [comment]
Sure, take a loot at this:  https://pytorch.org/mobile/android/
