### ISSUE TITLE
run the demo.py failed

### ISSUE THREAD

**Issue by shenjing023** [foamliu/Deep-Mobile-Matting#5]
I was download the BEST_checkpoint.tar, and run the demo.py, but something wrong:

Traceback (most recent call last):
  File "demo.py", line 69, in <module>
    checkpoint = torch.load(checkpoint)
  File "/home/search/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/search/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/serialization.py", line 613, in _load
    result = unpickler.load()
AttributeError: Can't get attribute 'DIMModel' on <module 'models' from '/data1/search/Mobile-Image-Matting/models/__init__.py'>

and I can't found any "DIMModel" in the repo?

**Comment by InternetMaster1** [comment]
@shenjing023 Did you find a solution for this?

**Comment by shenjing023** [comment]
@InternetMaster1 you can find the author another repo <Deep-Image-Matting-PyTorch>, there's DIMModel in that repo

**Comment by InternetMaster1** [comment]
@shenjing023 which is the correct link for BEST_checkpoint.tar? 

The one present in this library is giving a 404 error and the one present the other library gives dimmodel error and also it quite big in size for mobile usage. 

I am confused. Could you have a look at this issue I posted? Thanks

https://github.com/foamliu/Mobile-Image-Matting/issues/6

**Comment by shenjing023** [comment]
@InternetMaster1 Deep-Image-Matting-v2 is the right link I think

**Comment by InternetMaster1** [comment]
Deep-Image-Matting-v2 redirects to Deep-Image-Matting-PyTorch

In this link, the "BEST_checkpoint.tar" is **293 MB**
https://github.com/foamliu/Deep-Image-Matting-PyTorch/releases/BEST_checkpoint.tar

That would be unsuitable for mobile usage. Hence foamliu created this new library with a smaller model (but with worse SAD scores)

Small model (size: 23.5MB, FLOPs: 11.39GB, total params: 7.62 millions)

But the pre-trained model link for this is giving 404 error
https://github.com/foamliu/Deep-Mobile-Matting/releases/download/v1.0/BEST_checkpoint.tar

**Comment by InternetMaster1** [comment]
@shenjing023  Any tips?

**Comment by shenjing023** [comment]
@InternetMaster1 Sorry, may be you can find another repo and implement yourself.

**Comment by ucb-pb** [comment]
Where's the other repo with DIMModel ? This author has like 200 repos
